# name of the workflow
name: run python program

# define trigger
on:
  push:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print welcome message
        run: echo 'WELCOME TO GITHUB ACTIONS'
